### ISSUE TITLE
FOMA replacements

### ISSUE THREAD

**Issue by arademaker** [sdzx-1/typed-fsm#2]
https://fomafst.github.io

How much needs to be done to support FOMA features?

**Comment by sdzx-1** [comment]
I briefly looked at the foma below, and I think it can be divided into two parts:
1. Interactive part (REPL), using typed-fsm is good.
2. converting regular expressions to finite automata, this seems to be a purely algorithmic problem. I'm not sure if I should use typed-fsm.
